[package]
name = "yuumi"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
dotenvy = "0.15"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11.27", features = ["json"] }
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
